name: ClientWorker
catch_rules:
  - rule: _
    transform_rules:
      - search: ^http(s)?:\/\/((vercel|render|cfpages|netlify)\.cdn\.)?mzwing\.eu\.org
        replace:
          - https://vercel.cdn.mzwing.eu.org
          - https://render.cdn.mzwing.eu.org
          - https://netlify.cdn.mzwing.eu.org
          - https://cfpages.cdn.mzwing.eu.org
          - _
